name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t smaasadh/aasadh .
      - name: Publish image to Docker Hub
        run: docker push smaasadh/aasadh:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
      - name: Pull Image from Docker Hub
        run: docker pull smaasadh/aasadh:latest
      - name: Delete old container
        run: docker rm -f springboot-example-container || true
      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name springboot-example-container smaasadh/aasadh
